### ISSUE TITLE
ERROR: 0:6: 'isSelected' : syntax error

### ISSUE THREAD

**Issue by haopo2005** [YANG-H/Panoramix#13]
Hi,
I have trouble  of showgui during executing the function 'RunPanoramaReconstruction'. 
I have installed everything as you told. 
The error is  as  followed:

Have -858993460 buffers and -858993460 samples
QOpenGLShader::compile(Vertex): ERROR: 0:1: '130' : version number not supported

ERROR: 0:6: 'isSelected' : syntax error

*** Problematic Vertex shader source code ***
#version 130
#line 2
attribute highp vec3 position;
attribute highp vec3 normal;
attribute highp vec4 color;
attribute lowp vec2 texCoord;
attribute uint isSelected;
uniform highp mat4 viewMatrix;
uniform highp mat4 modelMatrix;
uniform highp mat4 projectionMatrix;
varying highp vec3 pixelPosition;
varying highp vec3 pixelNormal;
varying highp vec4 pixelColor;
varying lowp float pixelSelection;
void main(void)
{
    pixelPosition = position.xyz;
    pixelNormal = normal;
    pixelColor = color;
    gl_Position = projectionMatrix * viewMatrix * modelMatrix * vec4(position, 1
.0);
    pixelSelection = isSelected == 0u ? 0.0 : 1.0;
}

***
"ERROR: 0:1: '130' : version number not supported\nERROR: 0:6: 'isSelected' : sy
ntax error \n"
QOpenGLShader::compile(Fragment): ERROR: 0:1: '130' : version number not support
ed

*** Problematic Fragment shader source code ***
#version 130
#line 2
uniform sampler2D tex;
uniform lowp float bwColor;
uniform lowp float bwTexColor;
uniform highp vec3 panoramaCenter;
uniform highp float panoramaHoriCenterRatio;
uniform highp float panoramaAspectRatio;
varying highp vec3 pixelPosition;
varying highp vec3 pixelNormal;
varying highp vec4 pixelColor;
varying lowp float pixelSelection;
void main(void)
{
    highp vec3 direction = pixelPosition - panoramaCenter;
    highp float longi = atan(direction.y, direction.x);
    highp float lati = asin(direction.z / length(direction));
    highp float globalx = longi / 3.1415926535897932 / 2.0 + 0.5;
    highp float globaly = - lati / 3.1415926535897932 + 0.5;
    highp float texx = globalx;
    highp float texy =  (globaly / 2.0 - (0.25 - panoramaHoriCenterRatio * panor
amaAspectRatio)) / panoramaAspectRatio;
    if(texy < 0.0 || texy > 1.0){ discard; }
    highp vec2 texCoord = vec2(texx, texy);
    lowp vec4 texColor = texture2D(tex, texCoord);
    gl_FragColor = (pixelColor * bwColor + texColor * bwTexColor)       / (bwCol
or + bwTexColor);
    gl_FragColor.a = 1.0 - pixelSelection * 0.5;
}

***
"ERROR: 0:1: '130' : version number not supported\n"
""
QOpenGLShader::compile(Vertex): ERROR: 0:1: '130' : version number not supported

ERROR: 0:6: 'isSelected' : syntax error

*** Problematic Vertex shader source code ***
#version 130
#line 2
attribute highp vec4 position;
attribute highp vec3 normal;
attribute lowp vec4 color;
attribute lowp vec2 texCoord;
attribute uint isSelected;
uniform highp mat4 viewMatrix;
uniform highp mat4 modelMatrix;
uniform highp mat4 projectionMatrix;
varying lowp vec4 pixelColor;
varying lowp vec2 pixelTexCoord;
varying lowp float pixelSelection;
void main(void)
{
    gl_Position = projectionMatrix * viewMatrix * modelMatrix * position;
    pixelColor = color;
    pixelTexCoord = texCoord;
    pixelSelection = isSelected == 0u ? 0.0 : 1.0;
}

I am  not familiar with openGL Why the "isSelected" is syntax error?

Any reply will be helpful. thanks

**Comment by YANG-H** [comment]
Hi, there is an error saying: 
> QOpenGLShader::compile(Vertex): ERROR: 0:1: '130' : version number not supported

I think this may be the reason. I recommend checking two things:
1. Whether the GPU driver supports OpenGL 1.3, this can be verified using [OpenGL Extension Viewer](http://realtech-vr.com/admin/glview).
2. Whether the compiled Qt version supports OpenGL 1.3. The Qt version I use for this repo is shared [HERE](https://www.dropbox.com/s/jxv2ai2zludoay1/5.6-64bit-opengl.zip?dl=0).

**Comment by haopo2005** [comment]
wait a minute... Dose the program need GPU? I have run it on virutal host. so sad..
as for opengl1.3, I think the latest qt5.8 is enough.
And the version can be configured:
Panoramix-clean_ver\panoramix\src\ui.cpp, line 50
 // set opengl version
  QGLFormat glf = QGLFormat::defaultFormat();
  glf.setVersion(2, 0); // whatever version
  glf.setProfile(QGLFormat::CoreProfile);
  qDebug("OpenGL version: %d.%d", glf.majorVersion(), glf.minorVersion());
  glf.setSampleBuffers(true);
  glf.setSamples(16);
  QGLFormat::setDefaultFormat(glf);

OK, I will try to install the application on the real computer.
