### ISSUE TITLE
Problems about the structure of output mat file.

### ISSUE THREAD

**Issue by haopo2005** [YANG-H/Panoramix#14]
Hi,

I have closed the showgui options due to lack of gpu. and I have got obj and mat output file at present.
I dont understand the usage of depth,  planes and segs in the output mat file.

1.depth
the size of depth mat is quite similar with the size of panorama images.
the value of the mat ranges from 0.57 to 1.5 maybe.
I'd like to know its physical meaning. what's the relation between depth here and space depth?
What's the correspondence between  panorama  pixels and depth here?

2. planes
There is reconstruction flag in each planes structure. 
I dont understand the reconstruction process the each plane. It's critical for me.
Because the output obj file without texture information looks nice when it's rendered by meshlab.
I want to know how you make it.

3.segs
Dose segs represent the superpixels label? why is the size of this matrix quite similar with the size of panorama images? 

May I have your webchart ID?

**Comment by YANG-H** [comment]
1. `depth` - these are the depth distribution, each value in this distribution corresponds to a distance from the 3D structure to the viewpoint on the direction defined by the pixel;
2. `planes` - `.reconstructed = 0` means the plane is not reconstructed, otherwise the coefficients `[a,b,c]` of the plane equation `ax+by+cz=1` are given in `.plane_coeff`;
3. `segs` - these are the superpixel labels, the plane of each superpixel is given in `planes`.

**Comment by haopo2005** [comment]
all right, and where are the textures pictures of these superpixel or plane?
Do you use the zoomed panorama images as texture images?
besides glsl, do you have any suggestion about the tool to render , stitch or edit these model?

**Comment by YANG-H** [comment]
Yes, the textures are rendered through GLSL based on the zoomed panorama. 
The mapping from the panorama image to the 3D superpixel planes can be easily formulated in shading languages like GLSL, but it is not explicitly supported by common modeling tools. I'm afraid I don't have any other suggestions ...

**Comment by haopo2005** [comment]
thank you so much.
Can you tell me the basic process of "VisualizeReconstruction" function?
I dont know how to exhibit the model.
