### ISSUE TITLE
Program crashing with OpenCV assertion fails

### ISSUE THREAD

**Issue by Morpheus3000** [YANG-H/Panoramix#15]
Hello,

I was trying to get your code to run. After setting up everything as instructed, I was able to start up the program. For the first 2 runs, it gave the outputs till the superpixel segmentation, but then started crashing. As a result I was unable to get till the depth estimation. Strangely, after those two runs the program has started to crash even before showing any output that it was showing before. In both cases the console had the following errors:

file "E:/Panoramix/cache\Panorama\E..Projects.Pano3D.Panoramix.testdata.indoor_pano1_jpg_LayoutVersion0_on_on_on_off_off_off_off_options.cereal" saved
file "E:/Panoramix/cache\Panorama\E..Projects.Pano3D.Panoramix.testdata.indoor_pano1_jpg_LayoutVersion0_on_on_on_off_off_off_off_report.cereal" saved
file "E:/Panoramix/cache\Panorama\E..Projects.Pano3D.Panoramix.testdata.indoor_pano1_jpg_LayoutVersion0_on_on_on_off_off_off_off_preparation.cereal" loaded
file "E:/Panoramix/cache\Panorama\E..Projects.Pano3D.Panoramix.testdata.indoor_pano1_jpg_hcamsgcs_16_500_500_200.cereal" cannot be loaded!
[Message when executing '[~, ~, slabelConfMap] = gc(im);']:
Undefined function 'gc' for input arguments of type 'uint8'.

OpenCV Error: Assertion failed (!fixedType() || ((Mat*)obj)->type() == mtype) in cv::_OutputArray::create, file C:\build\master_winpack-build-win64-vc14\opencv\modules\core\src\matrix.cpp, line 2246

I am running on Windows 10, Visual Studio Community 2015 and MATLAB 2016a. Hope you can make sense of what's going wrong here.

**Comment by Morpheus3000** [comment]
I managed to solve the problem. The MATLAB Tools has the script named startup_sample.m. But the program expects startup.m. So fixing that discrepancy worked!

**Comment by haopo2005** [comment]
![qq 20170501230100](https://cloud.githubusercontent.com/assets/9463657/25582916/2b8f067e-2ec2-11e7-9099-4ec928eb3986.jpg)
![qq 20170501230111](https://cloud.githubusercontent.com/assets/9463657/25582915/2b82029e-2ec2-11e7-8636-90b6949859b6.jpg)
I have run his code successfully. If you have any problems about installation. I think I can help you :)

**Comment by Morpheus3000** [comment]
Thanks! I will post about issues here if I run into any! :)

**Comment by yhr971208** [comment]
> 
> 
> ![qq 20170501230100](https://cloud.githubusercontent.com/assets/9463657/25582916/2b8f067e-2ec2-11e7-9099-4ec928eb3986.jpg)
> ![qq 20170501230111](https://cloud.githubusercontent.com/assets/9463657/25582915/2b82029e-2ec2-11e7-8636-90b6949859b6.jpg)
> I have run his code successfully. If you have any problems about installation. I think I can help you :)

Hi,this is my first time to reproduce the paper. Could you give me some advice？

**Comment by yhr971208** [comment]
> 
> 
> I managed to solve the problem. The MATLAB Tools has the script named startup_sample.m. But the program expects startup.m. So fixing that discrepancy worked!

Hi,this is my first time to reproduce the paper. Could you give me some advice？I have some problems when I follow readme.md. When I was generated with vs2015, I encountered problems with error LNK 2001 and error LNK 2019.

**Comment by yhr971208** [comment]
> 
> 
> ![qq 20170501230100](https://cloud.githubusercontent.com/assets/9463657/25582916/2b8f067e-2ec2-11e7-9099-4ec928eb3986.jpg)
> ![qq 20170501230111](https://cloud.githubusercontent.com/assets/9463657/25582915/2b82029e-2ec2-11e7-8636-90b6949859b6.jpg)
> I have run his code successfully. If you have any problems about installation. I think I can help you :)

Hi,this is my first time to reproduce the paper. Could you give me some advice？I have some problems when I follow readme.md. When I was generated with vs2015, I encountered problems with error LNK 2001 and error LNK 2019.
